export const allLanguages = [
  { name: "الإنجليزية", code: "en" },
  { name: "الإسبانية", code: "es" },
  { name: "الفرنسية", code: "fr" },
  { name: "الألمانية", code: "de" },
  { name: "الصينية", code: "zh" },
  { name: "اليابانية", code: "ja" },
  { name: "الكورية", code: "ko" },
  { name: "العربية", code: "ar" },
  { name: "الروسية", code: "ru" },
  { name: "الهندية", code: "hi" },
  { name: "البرتغالية", code: "pt" },
  { name: "الإيطالية", code: "it" },
  { name: "الهولندية", code: "nl" },
  { name: "السويدية", code: "sv" },
  { name: "التركية", code: "tr" },
  { name: "البولندية", code: "pl" },
  { name: "اليونانية", code: "el" },
  { name: "العبرية", code: "he" },
  { name: "التايلاندية", code: "th" },
  { name: "الفيتنامية", code: "vi" },
  { name: "البنغالية", code: "bn" },
  { name: "الدانماركية", code: "da" },
  { name: "الفارسية", code: "fa" },
  { name: "الفنلندية", code: "fi" },
  { name: "الكانادية", code: "kn" },
  { name: "اللاتينية", code: "la" },
  { name: "الليتوانية", code: "lt" },
  { name: "المالايالامية", code: "ml" },
  { name: "النرويجية", code: "no" },
  { name: "الفرسية", code: "ps" },
  { name: "الرومانية", code: "ro" },
  { name: "الصربية", code: "sr" },
  { name: "التاميلية", code: "ta" },
  { name: "التشيكية", code: "cs" },
  { name: "الأوكرانية", code: "uk" },
  { name: "الأردية", code: "ur" },
  { name: "الويلزية", code: "cy" },
  { name: "الأرمينية", code: "hy" },
  { name: "البلغارية", code: "bg" },
  { name: "الكتالونية", code: "ca" },
  { name: "الكرواتية", code: "hr" },
  { name: "الإستونية", code: "et" },
  { name: "الغجرية", code: "hu" },
  { name: "الكمبودية", code: "km" },
  { name: "اللغة العربية المصرية", code: "arz" },
  { name: "اللغة الأمازيغية", code: "ber" },
  { name: "البوسنية", code: "bs" },
  { name: "الكانتونية", code: "yue" },
  { name: "الكورنيش", code: "kw" },
  { name: "الكردية", code: "ku" },
];

export const contentStyles = [
  "رسمي",
  "واقعي",
  "متفائل",
  "إحترافي",
  "ساخر",
  "سعيد",
  "متحمس",
  "حزين",
  "جاف",
  "نصيحة",
  "إحائي",
  "نادم",
  "مرح",
  "متشائم",
  "ودود",
];
